apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-c7zh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-c7zh@sha256:84d5e726469576b8b9d87962fd8983e37652cfa7a3e1ffd375e130233c0b7f36
        name: my-nodejs
        resources: {}
status: {}
